### ISSUE TITLE
Docker and makefiles

### ISSUE THREAD

**Issue by kcubero27** [pepecos/nextjs-preactjs-boilerplate#8]
Add a docker configuration and a make file with the necessary commands.
@jesugmz could help on this (probably using nginx)

**Comment by jesugmz** [comment]
Please, write down the following versions poiting the exact minimum required when needed (major, minor or patch):

- Node.js
- Nginx (I guess any stable should be enough)
- npm
- any other tool or service which its version is not controled by configuration (like any setted into package.json for example)

As well recurrent tasks in order to consider add them as Make targets.

**Comment by tomtobac** [comment]
Why there is a need of docker file? 🤔

**Comment by jesugmz** [comment]
> Why there is a need of docker file? thinking

Wasn't specified but yes, would be needed if we want to match specific versions, tools etc - to ge a custom Docker image. If there this need is not required, official images are enough.
